#配置分布式事务补偿
org:
  dromara:
    myth:
      serializer: kryo
        #repositorySupport : db
        #mythDbConfig :
        #driverClassName  : com.mysql.jdbc.Driver
        #url :  jdbc:mysql://localhost:3306/myth?useUnicode=true&amp;characterEncoding=utf8
        #username : root
        #password : 123456

      repositorySupport: redis
      mythRedisConfig:
        hostName: 127.0.0.1
        port    :     6379
        password: