spring:
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
                metadata: # 元数据，用于权限服务实时获取各个服务的所有接口
                    management.context-path: ${server.servlet.context-path:}${spring.mvc.servlet.path:}${management.endpoints.web.base-path:}
                    grayversion: maibaduoduo
            config:
                server-addr: 127.0.0.1:8848
                file-extension: yml
                shared-configs:
                    - dataId: common.yml
                      refresh: true
                    - dataId: redis.yml
                      refresh: true
                    - dataId: rabbitmq.yml
                      refresh: true
                enabled: true

# 服务管理配置
management:
    endpoints:
        web:
            exposure:
                include: "*"        #暴漏的接口，"*"表示所有web监控接口
                exclude:            #不暴漏的接口
            base-path: /  #监控根路径
    endpoint:
        health:
            show-details: ALWAYS

# info接口返回值
info:
    app:
        name: ${spring.application.name}
        version: 1.0.0
    java:
        version: ${java.version}
    #code:
    #   git: https://github.com/417511458/maibaduoduo
    #   gitee: https://gitee.com/majunwei2017/maibaduoduo
    domain: http://www.maibaduoduo.com

#排除数据表
maibaduoduo:
    database:
        ignoreTenantTables:
            - "sys_tenant"
            - "oauth_resource"
    interceptor:
        path: "/saas/**"