#Feign
spring:
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true
feign:
  hystrix:
    enabled: false
  compression:
    request:
      enable: true  # 配置请求GZIP压缩
      mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME TYPE
      min-request-size: 2048 # 配置压缩数据大小的下限
    response:
      enable: true # 配置响应GZIP压缩 FeignContentGzipEncodingAutoConfiguration
  client:
    config:
      default:    #服务名，填写default为所有服务
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: FULL
        #errorDecoder: ExceptionErrorDecoder  #自定义
        #retryer: ReginConfig #自定义
        requestInterceptors:
          - com.maibaduoduo.configuration.config.FeignRequestInterceptor
        decode404: false