spring:
  cloud:
    gateway:
      httpclient:
        wiretap: false
      httpserver:
        wiretap: false
      routes: #配置路由路径
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/api/u/**
          filters:
            - StripPrefix=2
            - name: Hystrix
              args:
                name: systemservice
                fallbackUri: forward:/error/fallback
        - id: system-service-app
          uri: lb://system-service-app
          predicates:
              - Path=/api/app/**
          filters:
              - StripPrefix=1
              - name: Hystrix
                args:
                  name: serviceapp
                  fallbackUri: forward:/error/fallback
        - id: system-service-file
          uri: lb://system-service-file
          predicates:
              - Path=/api/f/**
          filters:
              - StripPrefix=1
              - name: Hystrix
                args:
                  name: fileservice
                  fallbackUri: forward:/error/fallback
        - id: store-service
          uri: lb://store-service
          predicates:
              - Path=/api/store/**
          filters:
              - StripPrefix=1
              - name: Hystrix
                args:
                  name: storeservice
                  fallbackUri: forward:/error/fallback
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/saas/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: orderservice
                fallbackUri: forward:/error/fallback
      default-filters:
        - AddResponseHeader=i-helloworld,java
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,BAD_REQUEST,NOT_FOUND,UNAUTHORIZED,INTERNAL_SERVER_ERROR,GATEWAY_TIMEOUT
            methods: GET,POST
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials,RETAIN_UNIQUE  #服务内部跨域处理

#配置动态路由
maiba:
  gateway:
    dyroute:
      enable: true    #启动动态路由
      dyType: nacos   #启动nacos配置
      dy_group: DEFAULT_GROUP
