#Feign
feign:
   hystrix:
    enabled: true
   compression:
      request:
          enable: true  # 配置请求GZIP压缩
          mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME TYPE
          min-request-size: 2048 # 配置压缩数据大小的下限
      response:
          enable: true # 配置响应GZIP压缩 FeignContentGzipEncodingAutoConfiguration
   client:
    config:
      default:    #服务名，填写default为所有服务
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: full
        #errorDecoder: ExceptionErrorDecoder  #自定义
        #retryer: ReginConfig #自定义
        requestInterceptors:
          - FeignRequestInterceptor #自定义
        decode404: false

###全集配置就是是对所有的请求生效的
#ribbon
#其中“stu-provide”指明对哪个微服务的调用进行配置，当前配置使用随机策略，修改策略修改最后的类名即可
#stu-provide:
ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
     ConnectTimeout: 500 #请求连接超时时间
     ReadTimeout: 1000 #请求处理的超时时间
     kToRetryOnAllOperations: true #对所有请求都进行重试
     MaxAutoRetriesNextServer: 2 #切换实例的重试次数
     MaxAutoRetries: 1 #对当前实例的重试次数

###局部配置
 # Interval to refresh the server list from the source
 #kxtx-oms.ribbon.ServerListRefreshInterval=2000
 # Connect timeout used by Apache HttpClient
 #kxtx-oms.ribbon.ConnectTimeout=3000
 # Read timeout used by Apache HttpClien
