### xxl-job email
xxl.job:
  mail:
    host: smtp.163.com
    port: 25
    ssl: false
    username: ovono802302@163.com
    password: asdfzxcv
    sendNick: 《任务调度平台JOB》
  login:
    username: admin
    password: admin
  accessToken:
  i18n:
  # 以下是client 执行器端配置（注意：若不想配置调度器也是执行器，请自行参考xxl）
  admin:
    addresses: http://127.0.0.1:${server.port}/${spring.application.name}
  executor:
    appname: ${spring.application.name}
    ip: 127.0.0.1
    port: 8771
    registryLazy: 10000  # 延迟10秒注册，防止首次启动报错
    logpath: /${spring.application.name}/
    logretentiondays: -1
