### xxl-job email
xxl.job:
  mail:
    host: smtp.163.com
    port: 25
    ssl: false
    username: work@yeah.net
    password: 123456
    sendNick: <<任务调度JOB]>>
  login:
    username: admin
    password: admin
  accessToken:
  i18n:
  admin:
    addresses: http://127.0.0.1:${server.port}/${spring.application.name}
  executor:
    appname: ${spring.application.name}
    ip: 127.0.0.1
    port: 8771
    registryLazy: 10000  # 延迟10秒注册，防止首次启动报错
    logpath: /${spring.application.name}/
    logretentiondays: -1
