spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.boot: DEBUG
    org.springframework.web: DEBUG
    com.maibaduoduo: DEBUG
  config: classpath:logback-dev.xml
  file:
    path: ../logs