recover:
   application:
      list : alipay-service,wechat-service,pay-service
   serializer :
      support: kryo
   retry :
      max: 10
   zookeeper:
      host : localhost:2181
      sessionTimeOut : 3000
