server:
   port: 8888
   servlet:
     context-path: /admin

spring:
   application:
      name: raincat-admin
   profiles:
     active: db

tx:
  admin :
    userName : admin
    password : admin
  redis:
    hostName: localhost
    port : 6379
    password: 123456
    cluster : false
      # nodes: 127.0.0.1:70001;127.0.1:7002
      # redirects: 20
