#Feign
feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true
  compression:
    request:
      enable: true  # 配置请求GZIP压缩
      mime-types: text/xml,application/xml,application/json,text/event-stream # 配置压缩支持的MIME TYPE
      min-request-size: 2048 # 配置压缩数据大小的下限
    response:
      enable: true # 配置响应GZIP压缩 FeignContentGzipEncodingAutoConfiguration
  client:
    config:
      default:    #服务名，填写default为所有服务
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
        #errorDecoder: ExceptionErrorDecoder  #自定义
        #retryer: ReginConfig #自定义
        #requestInterceptors:
          #- com.maibaduoduo.configuration.config.FeignRequestInterceptor
        #decode404: false